### ISSUE TITLE
"Internal Error" after Sign up

### ISSUE THREAD

**Issue by bcurran3** [m0g/banban#2]
Hello.

Screenshot looks pretty, :-), decided to try it out but have problems.

When I try to Sign up and create an account for myself, I get this:
![image](https://github.com/user-attachments/assets/cdb06369-940c-4818-90c2-704544c4e3c0)

Logs are also showing:

> Listening on 0.0.0.0:3028
> PrismaClientKnownRequestError: 
> Invalid `prisma.user.findUnique()` invocation:
> The table `main.User` does not exist in the current database.
>     at Mn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
>     at Mn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
>     at Mn.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
>     at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
>     at async default (file:///app/build/server/chunks/13-CAdgq3RN.js:29:18)
>     at async handle_action_json_request (file:///app/build/server/index.js:2163:18)
>     at async resolve2 (file:///app/build/server/index.js:4625:24)
>     at async respond (file:///app/build/server/index.js:4517:22)
>     at async Array.ssr (file:///app/build/handler.js:1261:3) {
>   code: 'P2021',
>   clientVersion: '5.21.1',
>   meta: { modelName: 'User', table: 'main.User' }
> }

Docs are non-existent about user accounts. Is there a default admin account or first created account becomes the admin account?

MISC:
/app/prisma/db/banban.db file created with 0k size. Container is running as root and has permissions to the file.

> export DATABASE_URL='file:./db/banban.db'
> export HOME='/root'
> export HOSTNAME='banban'
> export NODE_ENV='production'
> export NODE_VERSION='20.18.1'
> export OLDPWD='/app'
> export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
> export PORT='3028'
> export PWD='/app/prisma/db'
> export SHLVL='1'
> export TERM='xterm'
> export TZ='America/Los_Angeles'
> export YARN_VERSION='1.22.22'

**Comment by m0g** [comment]
Hey there and thanks for your interest.

By default, there aren't any account created. You need to manually create one via the sign up page.
I also noticed, one step was missing from the readme for the development environment setup.

So it should be as following:

```bash
npm install
cp sample.env .env
npx prisma migrate dev
npm start
```

Let me know if this works.

**Comment by bcurran3** [comment]
I'm running via Docker. :-(

**Comment by m0g** [comment]
Could you tell me what command you used to set up the project?

**Comment by bcurran3** [comment]
I setup via an Ansible role. Here's the variables and task. Even if you don't know Ansible it should be readable.

defaults:
```
#
banban_enabled: false
banban_available_externally: false
banban_traefik_whitelist: "{{ lan }}"

# network
banban_port_http: "3028"
banban_hostname: "banban"

banban_data_directory: "{{ docker_home }}/banban"

# docker
banban_container_name: "banban"
banban_memory: "1G"

# homepage
banban_homepage_group: "Apps"
banban_homepage_icon: "banban.png"
banban_homepage_href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ banban_port_http }}"
banban_homepage_showStats: "false"

# watchtower
banban_watchtower_monitor_only: "true"

```
task:
```
---
- name: Start BanBan
  block:
    - name: Create BanBan Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ banban_data_directory }}"
        - "{{ banban_data_directory }}/db"
        - "{{ banban_data_directory }}/storage"

    - name: Create BanBan Docker Container
      docker_container:
        container_default_behavior: "compatibility"
        name: "{{ banban_container_name }}"
        hostname: "{{ banban_container_name }}"
        image: m0gd0ck/banban:latest
        pull: true
        volumes:
          - "{{ banban_data_directory }}/db:/app/prisma/db"
          - "{{ banban_data_directory }}/storage:/app/storage"
        ports:
          - "{{ banban_port_http }}:{{ banban_port_http }}"
        env:
          DATABASE_URL: "file:./db/banban.db"
          PORT: "{{ banban_port_http }}"
          NODE_ENV: "production"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        labels:
          com.centurylinklabs.watchtower.monitor-only: "{{ banban_watchtower_monitor_only }}"
          homepage.name: "banban"
          homepage.group: "{{ banban_homepage_group }}"
          homepage.icon: "{{ banban_homepage_icon }}"
          homepage.href: "{{ banban_homepage_href }}"
    #     homepage.description: "Self hosted Kanban board tool"
          homepage.siteMonitor: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ banban_port_http }}"
          homepage.server: "my-docker"
          homepage.container: "{{ banban_container_name }}"
          homepage.showStats: "{{ banban_homepage_showStats }}"
          traefik.enable: "{{ banban_available_externally | string }}"
          traefik.http.routers.banban.rule: "Host(`banban.{{ ansible_nas_domain }}`)"
          traefik.http.routers.banban.tls.certresolver: "letsencrypt"
          traefik.http.routers.banban.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.banban.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.frontend.middlewares: "{{ banban_hostname }}"
          traefik.http.routers.banban.middlewares: "{{ banban_hostname }}@docker"
          traefik.http.middlewares.banban.IPAllowList.sourcerange: "{{ banban_traefik_whitelist }}"
          traefik.http.services.banban.loadbalancer.server.port: "{{ banban_port_http }}"
          banban.tag.include: '^\d+\.\d+\.\d+$$'
          banban.link.template: "https://github.com/m0g/banban/releases/tag/$${major}.$${minor}.$${patch}"
        memory: "{{ banban_memory }}"

- name: Stop BanBan
  block:
    - name: Stop BanBan
      community.docker.docker_container:
        name: "{{ banban_container_name }}"
        state: absent
  when: banban_enabled is false

```
