### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by thommo17** [m0g/banban#3]
Hi,

I saw Banban on the Selfhosted newsletter and wanted to give it a go.

I'm not really sure about how to get it all started though.

I've used your docker-compose.yml and spun it up but can't create a new user.

Is there anything else needed to do with a fresh docker install to get it working?

Thanks

**Comment by m0g** [comment]
Hello,
You need the following docker-compose.yml

```yaml
services:
  banban:
    image: ghcr.io/m0g/banban:main
    container_name: banban
    restart: always
    environment:
      DATABASE_URL: file:./db/banban.db
      PORT: 3000
      NODE_ENV: production
    volumes:
      - ./docker/db:/app/prisma/db
      - ./docker/storage:/app/storage
    expose:
      - 3000
    ports:
      - '3000:3000'

```

And run those commands:

```bash
docker compose up -d
docker compose exec banban npx prisma migrate deploy
```

and then you should be able to create a new user via the sign up route.
Let me know if you are seeing any error
